development:
  adapter: mysql2
  database: potato_dev
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: potato_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: potato
  pool: 5
  timeout: 5000
